### ISSUE TITLE
How call these store data in loop 

### ISSUE THREAD

**Issue by fani625** [damogranlabs/dl-menu#1]
Thanks for this great work. And working as expected. 
Is variable store on this "miTestInt, miTestFloat, miTestChoice," for further use in program. and how can serial.print these variable.

**Comment by FranzBangar** [comment]
There's a getValue() method in every menu item class. So if you follow the example, in the main loop on line 104 you would add, for instance, Serial.print(miTestInt->getValue());

**Comment by fani625** [comment]
Thanks for reply and now working fine. Also I want to know if there is possibility to add :

1)  one 12 digit number like mobile number and other number as it is 03 digit. 
2) how can change the point position in float number like 24.365 instead of 2.436. for GPS locations

Thanks,

**Comment by FranzBangar** [comment]
These two would need a little more effort, probably new classes for mobile number and gps coordinate. I'll have a look.

**Comment by fani625** [comment]
I can get the GPS location like 24.36 with your example code if we can add 1 more digit after point  like      0 .123 it will be okay for me I try to read the library folder but can't get it because I am not good in programming.

Overall library cover all types of data and I am happy to work with it . I hope in new update it will cover 20x4 LCD with dynamic menu.

**Comment by FranzBangar** [comment]
I added a text menu item for any arbitrary input; you can then parse text to get data in any format. if you mean to update the library, be sure to check the example because there is a lot of changes in other objects as well.
