### ISSUE TITLE
LCD back light should off after few seconds 

### ISSUE THREAD

**Issue by fani625** [damogranlabs/dl-menu#3]
Dear,
I see in library that after 15 Sec automatically will come out from " menu.check() " I want to do the same thing with LCD backlight. When ever press any key back light should on and after 30 sec goes off.

I am using i2C LCD and successfully get the target with below sketch but same thing cannot manage with buttons. Can you explain little bit  regarding button states. 

void LCD_LED()
{

  if (P_State != lastP_State) {
    if (Pump_State == true || Pump_State == false  )
    {
      backlightState = true;
      backlightStartTime = millis();
      lcd.backlight(); // turn on backlight.
    }
    lastP_State = Pump_State;
  }
  if ( backlightState == true && millis() - backlightStartTime >= 30000 )
  {
    backlightState = false;
    lcd.noBacklight(); // turn off backlight
  }
} 
Thanks

**Comment by FranzBangar** [comment]
i suggest you write the logic in the if statement "if (menu.check()){ /* here */ }" and use the same logic as in the library. This way you won't have to modify the library but you'll have the same effect.
About your code:
 - this statement doesn't make any sense, it's true in any case: if (Pump_State == true || Pump_State == false )
 - you don't need the backlightState; you can tell that from backlightStartTime.
 - i'm not sure about the rest of your functions so i'll write a quick example off the top of my head (not tested!) just to give you an idea:

if(menu.check()){
  // there's something going on with the menu, therefore you need the backlight
  backlightStartTime = millis();
  lcd.backlight(); 
}
else{
  // you could either turn off the backlight right away
  // lcd.noBacklight();
  // or wait for the timeout
  if(millis() - backlightStartTime > 30000){
    lcd.noBacklight();
  }
}
