### ISSUE TITLE
 floating point value format (in menu) is changed after restart the arduino. 

### ISSUE THREAD

**Issue by fani625** [damogranlabs/dl-menu#5]
I noticed in floating point value format (in menu) is changed after restart the arduino. 
for example I set the value  +0.10000e+0 and exit from menu this value will be the same if I check it again next time. But if I restart the system its change to  **+1.00000e-1**

although both value  ( +0.10000e+0  and +1.00000e-1 ) are the same but its confusing some time. 
Kindly correct me if I am wrong in below code or it is library issue.

`// floating point value
#define DLM_FLOAT_DIGITS 6                             // number of digits
#define DLM_ADDR_TESTFLOAT 4                           // EEPROM address
const char miFloatLabel[] PROGMEM = {"Pressure [Pa]"}; // the label saved in PROGMEM

DLFloatMenuItem *miTestFloat = new DLFloatMenuItem(
  &lcd,
  miFloatLabel,
  DLM_ADDR_TESTFLOAT,
  DLM_FLOAT_DIGITS
);

#define DLM_ADDR_TESTFLOAT1 8                           // EEPROM address
const char miFloatLabel1[] PROGMEM = {"Pressure [Pb]"}; // the label saved in PROGMEM

DLFloatMenuItem *miTestFloat1 = new DLFloatMenuItem(
  &lcd,
  miFloatLabel1,
  DLM_ADDR_TESTFLOAT1,
  DLM_FLOAT_DIGITS
);
`

**Comment by FranzBangar** [comment]
This is expected behaviour. You can enter the same number in many ways (1.0e+0, 0.1e+1, 0.01e+2, and so on) but Arduino only saved the actual value, not the format entered. If you need to preserve the format as well, you might be better off saving a string instead of float.
